from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from PIL import Image, ImageDraw, ImageFont
from pathlib import Path
import textwrap

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'Sunrise_Dental_System_Report.docx'
ASSETS = ROOT / 'report_assets'
ASSETS.mkdir(exist_ok=True)

def font(size, bold=False):
    candidates = ['C:/Windows/Fonts/timesbd.ttf' if bold else 'C:/Windows/Fonts/times.ttf',
                  'C:/Windows/Fonts/arialbd.ttf' if bold else 'C:/Windows/Fonts/arial.ttf']
    for path in candidates:
        if Path(path).exists(): return ImageFont.truetype(path, size)
    return ImageFont.load_default()

def box(draw, xy, title, body='', fill='#F7F9FC', outline='#1F4E79'):
    x1,y1,x2,y2=xy; draw.rounded_rectangle(xy, radius=14, fill=fill, outline=outline, width=3)
    draw.text((x1+12,y1+10), title, fill='#102A43', font=font(22, True))
    y=y1+43
    for line in textwrap.wrap(body, width=max(14, int((x2-x1)/10))):
        draw.text((x1+12,y), line, fill='#243B53', font=font(17)); y+=21

def arrow(draw, a, b, label=''):
    draw.line([a,b], fill='#1F4E79', width=3)
    import math
    ang=math.atan2(b[1]-a[1],b[0]-a[0]); l=12
    p1=(b[0]-l*math.cos(ang-.45),b[1]-l*math.sin(ang-.45)); p2=(b[0]-l*math.cos(ang+.45),b[1]-l*math.sin(ang+.45))
    draw.polygon([b,p1,p2], fill='#1F4E79')
    if label: draw.text(((a[0]+b[0])/2,(a[1]+b[1])/2-18),label,fill='#7A3E00',font=font(15,True))

def usecase():
    im=Image.new('RGB',(1600,1040),'white'); d=ImageDraw.Draw(im)
    d.rectangle((260,50,1460,980),outline='#1F4E79',width=4); d.text((285,65),'Sunrise Dental System',fill='#102A43',font=font(28,True))
    actors=[('Staff',(55,330)),('Administrator',(45,700)),('External client',(60,900))]
    for name,(x,y) in actors:
        d.ellipse((x+25,y,x+55,y+30),outline='#102A43',width=3); d.line((x+40,y+30,x+40,y+85),fill='#102A43',width=3); d.line((x+10,y+55,x+70,y+55),fill='#102A43',width=3); d.line((x+40,y+85,x+15,y+115),fill='#102A43',width=3); d.line((x+40,y+85,x+65,y+115),fill='#102A43',width=3); d.text((x,y+122),name,fill='#102A43',font=font(18,True))
    cases=[('Log in',(410,150,680,220)),('Register appointment',(410,280,720,350)),('Search appointments',(410,410,720,480)),('Calculate and print bill',(410,540,740,610)),('View reports',(980,330,1240,400)),('Get API data',(980,600,1240,670)),('Validate input',(1000,150,1250,220)),('Check double booking',(1000,260,1320,330)),('Calculate treatment fee',(1000,470,1360,540))]
    for t,xy in cases: d.ellipse(xy,fill='#E8F1FA',outline='#1F4E79',width=3); d.text((xy[0]+15,xy[1]+23),t,fill='#102A43',font=font(17,True))
    for a,b in [((120,385),(410,315)),((120,385),(410,445)),((120,385),(410,575)),((120,755),(410,185)),((120,755),(980,365)),((120,755),(410,315)),((130,955),(980,635)),((720,315),(1000,185)),((720,315),(1000,295)),((740,575),(1000,505))]: arrow(d,a,b)
    for a,b,l in [((720,315),(1000,185),'<<include>>'),((720,315),(1000,295),'<<include>>'),((740,575),(1000,505),'<<include>>')]: d.text(((a[0]+b[0])//2,(a[1]+b[1])//2-35),l,fill='#7A3E00',font=font(14,True))
    d.text((900,760),'<<extend>> View reports requires Administrator role',fill='#7A3E00',font=font(17,True))
    p=ASSETS/'use_case.png'; im.save(p); return p

def classdiagram():
    im=Image.new('RGB',(1800,1300),'white'); d=ImageDraw.Draw(im)
    data=[('User','- userId: int\n- username: String\n- password: String\n- fullName: String\n- role: String','+ getUsername(): String\n+ getRole(): String', (70,70)),('Appointment','- appointmentNo: String\n- patientName: String\n- dentistName: String\n- treatmentType: String\n- appointmentDate: String\n- appointmentTime: String\n- status: String','+ getAppointmentNo(): String\n+ getStatus(): String',(540,70)),('Bill','- billId: int\n- appointmentNo: String\n- consultationFee: double\n- treatmentFee: double\n- totalAmount: double\n- paymentStatus: String','+ getTotalAmount(): double',(1050,70)),('DentalService','', '+ login(username,password): User\n+ registerAppointment(a): boolean\n+ getAppointment(no): Appointment\n+ calculateBill(type,fee): double\n+ saveBill(bill): boolean',(150,610)),('DentalServiceImpl','- userDao: UserDao\n- appointmentDao: AppointmentDao\n- billDao: BillDao','+ login(...): User\n+ registerAppointment(...): boolean',(720,610)),('AppointmentDao','', '+ isDoubleBooking(...): boolean\n+ saveAppointment(a): boolean\n+ findByAppointmentNo(no): Appointment\n+ generateNextAppointmentNo(): String',(1280,610)),('BillDao','', '+ saveBill(bill): boolean\n+ getTotalClinicRevenue(): double',(1280,960)),('TreatmentFeeFactory','', '+ getTreatmentBaseFee(type): double',(700,1010))]
    for title,attrs,ops,(x,y) in data:
        lines=attrs.count('\n')+ops.count('\n')+4; h=max(135,lines*27+38); d.rectangle((x,y,x+390,y+h),outline='#1F4E79',width=3,fill='#F7F9FC'); d.line((x,y+35,x+390,y+35),fill='#1F4E79',width=2); d.text((x+12,y+8),title,fill='#102A43',font=font(20,True)); yy=y+44
        for ln in attrs.split('\n'): d.text((x+10,yy),ln,fill='#243B53',font=font(15)); yy+=21
        d.line((x,yy+2,x+390,yy+2),fill='#1F4E79',width=2); yy+=8
        for ln in ops.split('\n'): d.text((x+10,yy),ln,fill='#243B53',font=font(15)); yy+=21
    for a,b,l in [((345,310),(345,610),'uses'),((735,310),(875,610),'creates'),((1245,310),(1450,610),'0..* bills'),((540,800),(720,800),'implements'),((1110,800),(1280,800),'uses'),((1110,870),(1280,1040),'uses'),((915,910),(895,1010),'uses')]: arrow(d,a,b,l)
    d.text((70,1240),'Legend: - private attribute   + public operation   solid arrows show navigable dependency/association.',fill='#102A43',font=font(17))
    p=ASSETS/'class_diagram.png'; im.save(p); return p

def sequence():
    im=Image.new('RGB',(1700,1120),'white'); d=ImageDraw.Draw(im); names=['Staff','RegisterAppointmentView','DentalServiceImpl','AppointmentDao','MySQL DB']; xs=[130,420,730,1040,1400]
    for x,n in zip(xs,names): d.rectangle((x-95,45,x+95,95),fill='#E8F1FA',outline='#1F4E79',width=3); d.text((x-80,62),n,fill='#102A43',font=font(16,True)); d.line((x,95,x,1060),fill='#8098AE',width=2)
    msgs=[(0,1,'1. Enter details and select Save'),(1,2,'2. registerAppointment(appointment)'),(2,3,'3. isDoubleBooking(dentist,date,time)'),(3,4,'4. SELECT existing appointment'),(4,3,'5. no record found'),(3,2,'6. false'),(2,3,'7. saveAppointment(appointment)'),(3,4,'8. INSERT appointment'),(4,3,'9. row inserted'),(3,2,'10. true'),(2,1,'11. true'),(1,0,'12. confirmation message')]
    y=145
    for i,j,label in msgs:
        arrow(d,(xs[i],y),(xs[j],y),label); y+=68
    d.rounded_rectangle((610,900,1320,1040),radius=14,fill='#FFF7E6',outline='#B7791F',width=3); d.text((635,925),'Alternative: if the dentist already has an active appointment,',fill='#7A3E00',font=font(17,True)); d.text((635,955),'DentalServiceImpl throws IllegalArgumentException and the view shows a warning.',fill='#7A3E00',font=font(17));
    p=ASSETS/'sequence_appointment.png'; im.save(p); return p

def set_cell_shading(cell, fill):
    tcPr=cell._tc.get_or_add_tcPr(); shd=OxmlElement('w:shd'); shd.set(qn('w:fill'),fill); tcPr.append(shd)
def set_cell_width(cell, width): cell.width=Inches(width)

def set_font(run, size=12, bold=False, italic=False):
    run.font.name='Times New Roman'; run._element.rPr.rFonts.set(qn('w:ascii'),'Times New Roman'); run._element.rPr.rFonts.set(qn('w:hAnsi'),'Times New Roman'); run.font.size=Pt(size); run.bold=bold; run.italic=italic
def para(doc, text='', bold=False, italic=False, align=None, space_after=6):
    p=doc.add_paragraph(); p.paragraph_format.line_spacing=1.5; p.paragraph_format.space_after=Pt(space_after); p.paragraph_format.space_before=Pt(0); p.alignment=align or WD_ALIGN_PARAGRAPH.JUSTIFY; r=p.add_run(text); set_font(r,12,bold,italic); return p
def heading(doc,text,level=1):
    p=doc.add_paragraph(style=f'Heading {level}'); p.paragraph_format.line_spacing=1.5; p.paragraph_format.space_before=Pt(12); p.paragraph_format.space_after=Pt(6); r=p.add_run(text); set_font(r,14,True); return p
def bullet(doc,text):
    p=doc.add_paragraph(style='List Bullet'); p.paragraph_format.line_spacing=1.5; p.paragraph_format.space_after=Pt(3); r=p.add_run(text); set_font(r,12); return p
def table(doc, headers, rows, widths=None):
    t=doc.add_table(rows=1, cols=len(headers)); t.alignment=WD_TABLE_ALIGNMENT.CENTER; t.style='Table Grid';
    for i,h in enumerate(headers):
        c=t.rows[0].cells[i]; c.text=''; set_cell_shading(c,'D9EAF7'); r=c.paragraphs[0].add_run(h); set_font(r,11,True); c.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
        if widths: set_cell_width(c,widths[i])
    trPr=t.rows[0]._tr.get_or_add_trPr(); header=OxmlElement('w:tblHeader'); header.set(qn('w:val'),'true'); trPr.append(header)
    for row in rows:
        cells=t.add_row().cells
        for i,val in enumerate(row):
            cells[i].text=''; r=cells[i].paragraphs[0].add_run(str(val)); set_font(r,10); cells[i].paragraphs[0].paragraph_format.line_spacing=1.15
            if widths: set_cell_width(cells[i],widths[i])
    doc.add_paragraph().paragraph_format.space_after=Pt(2); return t

def add_page_number(paragraph):
    paragraph.alignment=WD_ALIGN_PARAGRAPH.RIGHT; r=paragraph.add_run('Page '); set_font(r,10); fld=OxmlElement('w:fldSimple'); fld.set(qn('w:instr'),'PAGE'); paragraph._p.append(fld)

def main():
    use,cls,seq=usecase(),classdiagram(),sequence()
    doc=Document(); sec=doc.sections[0]; sec.page_width=Inches(8.27); sec.page_height=Inches(11.69); sec.left_margin=Inches(1.5); sec.right_margin=Inches(1); sec.top_margin=Inches(1); sec.bottom_margin=Inches(1)
    styles=doc.styles; styles['Normal'].font.name='Times New Roman'; styles['Normal']._element.rPr.rFonts.set(qn('w:ascii'),'Times New Roman'); styles['Normal'].font.size=Pt(12)
    footer=sec.footer.paragraphs[0]; add_page_number(footer)
    for style_name in ['Heading 1','Heading 2','Heading 3']:
        style=styles[style_name]; style.font.name='Times New Roman'; style._element.rPr.rFonts.set(qn('w:ascii'),'Times New Roman'); style.font.size=Pt(14); style.font.bold=True
    p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; p.paragraph_format.space_before=Pt(140); r=p.add_run('SUNRISE DENTAL SYSTEM'); set_font(r,20,True)
    p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; r=p.add_run('System Design, Development, Testing and Version-Control Report'); set_font(r,14,True)
    para(doc,'Coursework report based on the implemented Java Swing and MySQL application',align=WD_ALIGN_PARAGRAPH.CENTER,space_after=18)
    para(doc,'Student Name: ______________________________',align=WD_ALIGN_PARAGRAPH.CENTER)
    para(doc,'Student ID: _________________________________',align=WD_ALIGN_PARAGRAPH.CENTER)
    para(doc,'Module: Advanced Programming',align=WD_ALIGN_PARAGRAPH.CENTER)
    para(doc,'Submission date: ____________________________',align=WD_ALIGN_PARAGRAPH.CENTER)
    doc.add_page_break()
    heading(doc,'Executive Summary')
    para(doc,'Sunrise Dental System is a desktop application designed to support daily activities in a small dental clinic. The system allows authorised staff to log in, register appointments, search records, calculate treatment charges, produce a receipt and view financial reports. It uses Java Swing for the user interface, JDBC to connect to a MySQL database and a small embedded REST web service for distributed access. The design follows a presentation, service and data-access separation. This report explains the design, implementation, testing strategy and Git workflow in clear language. It also identifies realistic limitations and improvement opportunities. The aim is not only to describe code, but to show that the design decisions meet the learning outcomes.')
    heading(doc,'Contents')
    for x in ['1. Introduction and requirements','2. Task A - UML design and design decisions','3. Task B - system architecture, patterns and database','4. Task C - testing and test-driven development','5. Task D - GitHub, version control and deployment','6. Critical evaluation and conclusion','References','Appendix A - requirement traceability','Appendix B - evidence checklist']:
        para(doc,x,align=WD_ALIGN_PARAGRAPH.LEFT,space_after=2)
    heading(doc,'1. Introduction and Requirements')
    para(doc,'The clinic needs a reliable way to manage patient visits without relying on paper records. Reception staff need to make an appointment quickly, avoid allocating one dentist to two patients at the same time, find an existing visit and prepare a bill. The clinic administrator needs a simple view of revenue and appointment activity. These requirements were translated into a desktop system because the initial users work at one clinic reception desk and benefit from a direct, keyboard-friendly interface.')
    para(doc,'The implemented system has six main screens: LoginView, MainDashboardView, RegisterAppointmentView, SearchAppointmentView, BillingView and ReportsView. It stores users, appointments, bills and treatment fee information in MySQL. The functional scope is deliberately focused: it is a clinic administration system, not a full electronic medical-record system. For example, clinical notes, stock control, insurance claims and online patient self-booking are outside the present scope.')
    heading(doc,'2. Task A - UML Design and Design Decisions')
    heading(doc,'2.1 Assumptions',2)
    for x in ['A user is either an ADMIN or STAFF member; both can carry out reception work, while financial reports are intended for administrators.','Each appointment belongs to one patient visit, one selected dentist and one treatment type.','A dentist may have many appointments, but may not have two active appointments at the same date and time.','A bill is created from an existing appointment. Amounts are shown in Sri Lankan Rupees (LKR).','The REST API is a demonstration of distributed web services for the coursework; production use would require authentication and stronger privacy controls.']:
        bullet(doc,x)
    heading(doc,'2.2 Use Case Diagram',2)
    para(doc,'Figure 1 identifies the actors and their goals. Staff interact with appointment registration, searching and billing. The administrator has the same core access plus reporting. An external client represents a permitted API consumer. The <<include>> relationships are used where a compulsory internal action occurs every time: registration includes validation and the double-booking check, while billing includes treatment-fee calculation. Reporting is modelled as an extension of the normal dashboard capability because it depends on an administrator role. This notation follows UML use-case concepts described by Object Management Group (2017).')
    doc.add_picture(str(use),width=Inches(5.7)); doc.paragraphs[-1].alignment=WD_ALIGN_PARAGRAPH.CENTER; para(doc,'Figure 1. Use case diagram for Sunrise Dental System.',italic=True,align=WD_ALIGN_PARAGRAPH.CENTER)
    heading(doc,'2.3 Class Diagram',2)
    para(doc,'The class diagram reflects the code structure rather than an idealised design. User, Appointment and Bill are entity classes holding the data used by the system. DentalService is the business-facing interface. DentalServiceImpl coordinates user authentication, booking checks and billing operations. AppointmentDao and BillDao isolate SQL operations. TreatmentFeeFactory supplies a treatment fee. Private fields protect each object state, and public getters or service methods provide controlled access. The key multiplicity is that an appointment can have zero or more bills in the current database design; this is technically possible but should be restricted to zero or one paid bill in a future version.')
    doc.add_picture(str(cls),width=Inches(5.7)); doc.paragraphs[-1].alignment=WD_ALIGN_PARAGRAPH.CENTER; para(doc,'Figure 2. Simplified implementation class diagram.',italic=True,align=WD_ALIGN_PARAGRAPH.CENTER)
    heading(doc,'2.4 Sequence Diagram: registering an appointment',2)
    para(doc,'Figure 3 describes the most important risk-controlled workflow. The staff member enters data in the form, which calls the service layer. The service first asks AppointmentDao whether the selected dentist already has an active appointment at the requested time. If not, the service calls saveAppointment and the DAO inserts the record in MySQL. The confirmation is then returned to the user interface. The alternative path is also important: a duplicate booking causes an IllegalArgumentException and the form displays a warning rather than storing invalid data. Separating view, service and DAO responsibilities makes the sequence easier to understand and test.')
    doc.add_picture(str(seq),width=Inches(5.7)); doc.paragraphs[-1].alignment=WD_ALIGN_PARAGRAPH.CENTER; para(doc,'Figure 3. Sequence diagram for appointment registration.',italic=True,align=WD_ALIGN_PARAGRAPH.CENTER)
    heading(doc,'2.5 Design evaluation',2)
    para(doc,'The UML models support one another. The use case diagram defines what stakeholders expect; the class diagram allocates responsibility to objects; and the sequence diagram explains how one critical use case actually moves through those objects. This reduces ambiguity before implementation. The current design is understandable and appropriate for a coursework project. However, the design could be strengthened by using LocalDate and LocalTime in the model instead of String, by adding a Patient class, and by enforcing database constraints. These changes would prevent more errors at the data level instead of relying mainly on the user interface.')
    para(doc,'The diagram deliberately separates a patient visit from the user who creates it. The current Appointment model stores patient name, address and contact number directly because the system is designed around one-off appointment entry. This keeps the initial system simple, but it makes repeat-patient history harder to manage. A future Patient entity would own stable identity and contact fields, while Appointment would reference patientId. In UML terms, a Patient would have a one-to-many association with Appointment. Treatment is also represented as a model class even though the current fee lookup is implemented through a factory; this gives a clear route to add treatment maintenance later without changing the appointment interface.')
    heading(doc,'3. Task B - System Architecture, Patterns and Database')
    heading(doc,'3.1 Interactive interfaces and validation',2)
    para(doc,'The application is interactive because each main task has a dedicated Swing window. The login screen requests credentials; the dashboard gives clear task buttons; the registration form obtains patient details, dentist, treatment, date and time; the search screen displays a table of matching appointments; the billing screen calculates the charge and previews a receipt; and the reporting screen provides revenue and appointment statistics. This separation keeps each interface focused and reduces user mistakes.')
    para(doc,'Validation is applied before saving an appointment. Required fields cannot be blank. InputValidator checks that the phone number has a Sri Lankan mobile format, that the date follows YYYY-MM-DD, and that the time follows 24-hour HH:mm notation. DentalServiceImpl then performs a business validation by checking for a double booking. These are useful controls because they protect data quality at two levels. A limitation is that the date pattern does not prove that a calendar date is real; therefore LocalDate.parse should replace the present regular-expression-only check.')
    heading(doc,'3.2 Three-tier architecture',2)
    para(doc,'The system follows a practical three-tier architecture. The presentation tier consists of Swing views and contains display logic and user messages. The business tier is DentalService and DentalServiceImpl, which carries out booking and billing rules. The data tier is made up of DAOs and DBConnection, which send prepared SQL statements to MySQL. Prepared statements are a positive design choice because they separate values from SQL text and reduce SQL-injection risk. The REST service is a separate access point which calls the same service layer rather than bypassing core rules.')
    table(doc,['Layer','Main classes','Responsibility'],[['Presentation','LoginView, MainDashboardView, RegisterAppointmentView, SearchAppointmentView, BillingView, ReportsView','Collect input, show feedback and display data.'],['Business','DentalService, DentalServiceImpl','Coordinate use cases and enforce double-booking rule.'],['Data','UserDao, AppointmentDao, BillDao, DBConnection','Persist and retrieve information through JDBC.'],['Integration','DentalRestWebService','Expose selected data through HTTP JSON endpoints.']], [1.15,2.3,2.25])
    heading(doc,'3.3 Design patterns',2)
    para(doc,'Several patterns are visible in the implementation. First, DBConnection uses the Singleton idea: one static access point provides a database connection. It is easy to use in a small system, although a connection pool would be safer for a larger multi-user system. Second, each DAO is a Data Access Object. It keeps SQL out of the user interface and makes database code easier to replace or test. Third, DentalService acts as a Service Layer and façade: views call one business-facing interface instead of coordinating multiple DAOs directly. Finally, TreatmentFeeFactory is a Factory-style utility that obtains a treatment base fee from the database and falls back to a predefined mapping when necessary.')
    table(doc,['Pattern','Evidence in the system','Benefit','Critical evaluation'],[['DAO','AppointmentDao, BillDao and UserDao','Separates SQL from UI','Good separation; DAO errors should be returned as meaningful exceptions rather than empty values.'],['Service Layer / Facade','DentalService and DentalServiceImpl','Central location for business rules','Allows reuse by Swing and REST clients; role checks should also be enforced here.'],['Singleton','DBConnection.getConnection()','Simple shared access point','Current try-with-resources calls close the shared connection; a pooled datasource is preferable.'],['Factory','TreatmentFeeFactory','Central fee selection','Fallback fee makes the demo resilient; treatment records should be managed through a DAO.']], [1.0,1.65,1.45,1.6])
    heading(doc,'3.4 Database design and reports',2)
    para(doc,'The database has four conceptual tables: users, appointments, bills and treatments. Users store login identity and role. Appointments store the appointment number, patient details, dentist, treatment, date, time, creator and status. Bills contain fee components, total, payment status and billing time. Treatments contain a named base fee. The appointment number links an appointment to a bill. For a future schema, appointments.appointment_no should be unique, bills.appointment_no should be unique where only one bill is permitted, and a composite rule should prevent conflicting active dentist slots. Database-side constraints are important because two staff members may use the system at the same time.')
    para(doc,'The ReportsView adds value by summarising total paid revenue and total recorded appointments, followed by a recent appointment log. This supports simple managerial decisions, for example whether demand is increasing or which treatments appear frequently. Suitable next reports are daily appointment schedules by dentist, unpaid or pending bills, monthly treatment revenue and cancelled-appointment rates. Report outputs should eventually use date filters and export to PDF or CSV.')
    heading(doc,'3.5 Distributed application and web service',2)
    para(doc,'DentalRestWebService uses Java HttpServer and starts from AppMain. It supplies GET endpoints for all appointments, total revenue and service status. The JSON response allows a future website or mobile application to obtain information without coupling directly to the Java desktop UI. This meets the distributed-application requirement at a demonstrator level. It must not be treated as production ready: it starts before the user logs in, returns patient data without authentication, sets Access-Control-Allow-Origin to *, and builds JSON manually. A safe production version would use token-based access, role-based permissions, a JSON library, HTTPS, limited CORS and audit logging.')
    para(doc,'The service boundary is also valuable from an architectural viewpoint. A web client does not need to know how a JDBC query works and the desktop UI does not need to know how JSON is produced. Both use the business layer as a common source of behaviour. This avoids a common error in student projects where the web endpoint repeats SQL and slowly diverges from the desktop rules. The status endpoint is particularly useful for operational checks because it can be called by a monitoring tool. For real clinical usage, an endpoint should return only the minimum data required, paginate large appointment lists and return standard HTTP error responses rather than silently returning an empty list after a database failure.')
    heading(doc,'4. Task C - Testing and Test-Driven Development')
    heading(doc,'4.1 Test rationale and approach',2)
    para(doc,'Testing should focus first on the rules that can cause financial loss, privacy problems or unusable data. Unit tests are appropriate for InputValidator and treatment-fee calculation because they are deterministic. Service tests should verify double-booking behaviour with mocked or test DAOs. Integration tests should run DAO queries against a separate disposable test database, never the clinic production database. Finally, manual user-interface tests should confirm that error messages, navigation and print-preview behaviour are understandable. JUnit 5 is already declared as a test dependency in the Maven project and provides assertions and lifecycle support for automated Java testing (JUnit Team, 2025).')
    heading(doc,'4.2 TDD process used/planned',2)
    para(doc,'Test-driven development (TDD) means writing a small failing test before writing the production code that makes it pass. The cycle is red, green and refactor: write a failing test for one rule; implement only enough code for the test to pass; then improve the code while keeping the tests green. For example, first write a test that rejects 077123456; then implement the phone rule; then refactor the regular expression if needed. For an existing project, the honest approach is to introduce TDD incrementally. Existing behaviour should first be captured with characterisation tests, then new changes such as stricter date validation should follow red-green-refactor. The current repository contains the JUnit dependency but no visible test classes, so automated test evidence must be added before claiming that all tests pass.')
    table(doc,['ID','Test and rationale','Test data','Expected result'],[['UT-01','Valid Sri Lankan mobile number','0771234567','InputValidator returns true.'],['UT-02','Reject too-short mobile number','077123456','InputValidator returns false.'],['UT-03','Valid 24-hour time','14:30','InputValidator returns true.'],['UT-04','Reject invalid time','25:70','InputValidator returns false.'],['UT-05','Fee calculation for known treatment','Root Canal Treatment; consultation 2500','Total equals 20500.00.'],['ST-01','Prevent double booking','same dentist/date/time as existing appointment','Service throws validation error; no INSERT occurs.'],['IT-01','Save and retrieve appointment','valid appointment APT-1001','Record is returned with matching fields.'],['IT-02','Revenue only includes paid bills','one PAID bill and one PENDING bill','Revenue excludes pending bill.'],['UI-01','Blank registration field','empty patient name','Warning shown and no save occurs.'],['API-01','Status endpoint','GET /api/status','HTTP 200 and service status JSON.']], [0.55,2.5,1.55,1.6])
    heading(doc,'4.3 Automated test examples and execution plan',2)
    para(doc,'The following examples should be placed under src/test/java. A test class named InputValidatorTest should use assertTrue(InputValidator.isValidPhone("0771234567")) and assertFalse(InputValidator.isValidPhone("07123")). A TreatmentFeeFactory test should inject or mock its data source where possible; because the current factory calls the database statically, it is harder to isolate. Refactoring it behind a TreatmentRepository interface would make TDD easier. Maven should be installed or the Maven Wrapper added, then mvn test should run locally and in GitHub Actions. The result screen or console output should be captured and inserted into the final submitted report as evidence. At review time, Maven was not available in the local environment, therefore this report does not claim successful automated execution.')
    heading(doc,'4.4 Test completion criteria',2)
    para(doc,'The test plan is complete only when every high-risk rule has at least one passing automated test, all integration tests run against a dedicated test database, failures are corrected and rerun, and a human performs the UI acceptance checks. Defects should be recorded with an ID, severity, steps to reproduce, expected result, actual result and resolution commit. This creates traceability between requirements, tests and code changes.')
    para(doc,'Boundary-value analysis is especially suitable for the validator tests. For a ten-digit local mobile number, tests should cover a valid ten-digit value, a nine-digit value, an eleven-digit value, an unexpected prefix, spaces and null. For time, test 00:00, 23:59, 24:00 and malformed separators. Equivalence partitioning reduces unnecessary cases by grouping inputs that should behave the same way. Booking tests should include scheduled, cancelled and completed appointment statuses because the SQL rule excludes CANCELLED records. Test data must use fictional names and numbers so that no personal data is included in a public GitHub repository or screenshot.')
    heading(doc,'5. Task D - GitHub, Version Control and Deployment')
    para(doc,'Git is used to record a history of project changes, enabling earlier versions to be compared or restored (Chacon and Straub, 2014). The repository history already shows incremental UI commits, including login styling and readability improvements. This is a good start because it shows development did not happen as one final upload. To meet the full marking criteria, the repository must be public, the final report must include its exact URL, and the history should show meaningful changes on different days. Insert the actual public repository URL here before submission: https://github.com/[your-account]/SunriseDentalSystem.')
    heading(doc,'5.1 Recommended workflow',2)
    for x in ['Create an issue for a feature or defect, for example “Add strict calendar-date validation”.','Create a descriptive branch, such as feature/date-validation or fix/duplicate-bill.','Write tests first where practical, commit the test, implement the change, and commit the implementation with a clear message.','Push the branch, open a pull request, review the diff and allow GitHub Actions to run mvn test.','Merge only after checks pass; tag assessed milestones such as v1.0.0, v1.1.0 and v1.2.0.','Deploy or package the final JAR from a release/tag and document how it was demonstrated.']:
        bullet(doc,x)
    heading(doc,'5.2 Suggested commit history and CI/CD evidence',2)
    table(doc,['Version','Illustrative change','Evidence to include'],[['v1.0.0','Initial Swing screens, database connection and login','GitHub release/tag and initial commit.'],['v1.1.0','Appointment validation and double-booking rule','Commit links, test screenshot and updated UML.'],['v1.2.0','Billing, reports and REST endpoints','Release notes and API demonstration screenshot.'],['v1.3.0','Automated tests and GitHub Actions workflow','Actions build badge and successful workflow run.']], [1.0,2.7,2.5])
    para(doc,'A suitable GitHub Actions workflow checks out the repository, installs Java 17, caches Maven dependencies and runs mvn test. The project should also include a README with prerequisites, database schema/setup instructions, sample users without real passwords, API endpoints, how to run the application and the report link. No external deployment should be claimed unless a real public release or hosted service has been created. For a desktop system, publishing a tagged release containing the runnable JAR and setup guide is an appropriate deployment demonstration.')
    para(doc,'Good commit messages explain why a change exists, not only which file changed. For example, “fix(booking): reject occupied dentist slots” is more informative than “update code”. Small commits make it easier to review a defect and to return to a stable version. A branch protects the default branch while a feature is under development; a pull request creates a documented discussion and review point; a tag records an assessed release. Screenshots for the report should show the GitHub commit graph, a pull request or branch comparison, the release page and the Actions result. These are stronger evidence than a single screenshot of the repository home page.')
    heading(doc,'6. Critical Evaluation and Conclusion')
    para(doc,'Sunrise Dental System achieves a coherent core workflow for a dental clinic. Its strengths are a focused interface, understandable object separation, prepared SQL statements, input validation, a useful reporting view, and a clear demonstration of a distributed service. The use of DAO, service layer, singleton and factory ideas gives the code structure beyond a single monolithic program. The UML design shows how requirements are translated into responsibilities and interactions.')
    para(doc,'The main weaknesses are important to acknowledge. Passwords are handled in plain text; database connection settings are hard-coded; the API is unauthenticated; appointment IDs are generated using a count and may clash; bills can be duplicated; database work may block the Swing event thread; and no test classes or schema migration files are currently visible. These are not reasons to discard the system, but they are a realistic improvement backlog. The highest-priority next step is security: move configuration out of code, hash passwords and restrict API data. Next, enforce database constraints and add JUnit tests with continuous integration. These changes would make the project stronger technically and provide the evidence required for excellent marks.')
    heading(doc,'6.1 Security, ethics and maintainability reflection',2)
    para(doc,'A clinic system handles personal data, so technical quality is also an ethical responsibility. Patient names, contact numbers and appointment details should be visible only to staff who need them to perform their role. The current REST demonstration endpoint returns appointment information without access control; this is acceptable only for a tightly controlled classroom demonstration with non-real data. Before real use, the system should record who accessed or changed a record, automatically end inactive sessions, encrypt data in transit and follow the organisation’s data-retention policy. Password hashing is essential because a database leak must not expose reusable passwords.')
    para(doc,'Maintainability is improved when one business rule has one clear home. The current double-booking rule is correctly located in DentalServiceImpl rather than duplicated in every view. In contrast, some database failure paths return false, null or zero. This can hide an operational error by making it look like there are no appointments or no revenue. A dedicated exception such as DataAccessException, together with user-friendly error messages and structured logs, would distinguish system failures from valid empty results. The same principle applies to the date and time fields: using typed LocalDate and LocalTime values throughout the business layer would make invalid values impossible after validation.')
    heading(doc,'6.2 Prioritised improvement roadmap',2)
    table(doc,['Priority','Improvement','Reason and measurable outcome'],[['1','Hash passwords; move DB settings to environment configuration; authenticate REST endpoints','Removes the most serious confidentiality risk. A login test should verify hashed credential comparison and an API test should reject anonymous access.'],['2','Add database unique constraints and a transaction around booking/billing','Prevents duplicate appointment slots and duplicate bills even under simultaneous use.'],['3','Create JUnit unit/service/DAO tests and GitHub Actions workflow','Produces repeatable evidence that business rules remain correct after change.'],['4','Use LocalDate, LocalTime and BigDecimal','Improves data validity and avoids money rounding errors.'],['5','Move DAO calls off the Swing event-dispatch thread','Keeps the interface responsive when the database is slow.']], [0.7,2.2,3.2])
    heading(doc,'References')
    refs=['Chacon, S. and Straub, B. (2014) Pro Git. 2nd edn. Available at: https://git-scm.com/book/en/v2.html (Accessed: 28 August 2026).','JUnit Team (2025) JUnit 5 User Guide. Available at: https://junit.org/junit5/docs/current/user-guide/ (Accessed: 28 August 2026).','Object Management Group (2017) Unified Modeling Language (UML), Version 2.5.1. Available at: https://www.omg.org/spec/UML/2.5.1/About-UML (Accessed: 28 August 2026).','Oracle (2025) Java Platform, Standard Edition Documentation. Available at: https://docs.oracle.com/en/java/ (Accessed: 28 August 2026).','Pressman, R.S. and Maxim, B.R. (2019) Software Engineering: A Practitioner’s Approach. 9th edn. New York: McGraw-Hill.']
    for r in refs: para(doc,r,align=WD_ALIGN_PARAGRAPH.LEFT,space_after=4)
    heading(doc,'Appendix A - Requirement Traceability')
    table(doc,['Requirement','Design / code evidence','Verification evidence'],[['Interactive inputs and validation','RegisterAppointmentView and InputValidator','UT-01 to UT-04; UI-01.'],['Database storage','MySQL JDBC connection; DAO classes','IT-01 and IT-02.'],['Distributed web service','DentalRestWebService endpoints','API-01 plus browser/curl screenshot.'],['Design patterns','DAO, Service Layer, Singleton, Factory','Class diagram and code review.'],['Reports','ReportsView uses appointment and bill data','Admin report screenshot and revenue test.'],['TDD and automation','JUnit test classes and Maven/GitHub Actions','mvn test output and Actions run.'],['Version control','Git commits, branches, PRs, tags/releases','Public GitHub URL and screenshots.']], [1.35,2.8,2.05])
    heading(doc,'Appendix B - Submission Evidence Checklist')
    for x in ['Replace student name, ID, date and the GitHub placeholder URL.','Add screenshots of the running login, registration, billing, reports and REST API screens.','Add screenshots showing Maven/JUnit tests passing and a successful GitHub Actions workflow.','Add the real database schema SQL file to the repository and cite it in the README.','Check that every source used in the final report is in the Harvard reference list.','Export a final PDF only after the Word document has been checked for page breaks, diagrams and page numbers.']:
        bullet(doc,x)
    descriptions=['Use case diagram showing Staff, Administrator and external client interactions with Sunrise Dental System.','Class diagram showing the User, Appointment, Bill, service, DAO and fee-factory classes and their dependencies.','Sequence diagram showing appointment registration from a staff member through the view, service, DAO and MySQL database.']
    for shape, description in zip(doc.inline_shapes, descriptions):
        shape._inline.docPr.set('descr', description)
    doc.core_properties.title='Sunrise Dental System Report'; doc.core_properties.author='Student'
    doc.save(OUT)
    print(OUT)

if __name__=='__main__': main()
